### ISSUE TITLE
No need to check both lengths

### ISSUE THREAD

**Issue by pakim249CAL** [programmablewealth/gotchiverse-crowdfarming-contracts#1]
https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/2bdf3c867428e5307e70dbcd8cc47dfbd787abe3/contracts/facets/CrowdFundingFacet.sol#L36

Since theres a check to make sure that both lengths are equal, only one length needs to be checked > 0

**Comment by programmablewealth** [comment]
Resolved. Thanks fren.

https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/commit/6487d7dca7cb93cd1448b315369956f2fff5203a
