### ISSUE TITLE
Provide internal entry point

### ISSUE THREAD

**Issue by pakim249CAL** [programmablewealth/gotchiverse-crowdfarming-contracts#12]
https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/b93894b19c37717edabae989408ac08a2ddcb1da/contracts/facets/CrowdFundingFacet.sol#L95

This function only has an external entry point. Because of this, the function requires calling this.calculateBudget. This is dangerous when combined with LibMeta, as LibMeta relies on making external function calls to address(this) to manipulate sender address.

I recommend either:

1. Making the function public so that you don't have to make an external call to your own contract.
2. Making a library that would contain all internal logic. This would be useful if you ever added more facets to your contract, as this internal functionality can be shared between facets.

**Comment by jarrodlilkendey** [comment]
Fixed - https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/commit/df714892e3e741640007eff7ff6b1b8a40cc3f70
