### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by pakim249CAL** [programmablewealth/gotchiverse-crowdfarming-contracts#2]
https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/6487d7dca7cb93cd1448b315369956f2fff5203a/contracts/facets/CrowdFundingFacet.sol#L35

I recommend using the format: "CrowdFundingFacet: Error" as this helps immensely with figuring out from which facets errors come from.

**Comment by programmablewealth** [comment]
implemented 👍
