### ISSUE TITLE
Reduce chance of mistakes by defining struct with named fields

### ISSUE THREAD

**Issue by pakim249CAL** [programmablewealth/gotchiverse-crowdfarming-contracts#3]
https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/6487d7dca7cb93cd1448b315369956f2fff5203a/contracts/facets/CrowdFundingFacet.sol#L51

I recommend defining structs like this:

FarmingOperation(
{
operationId: newOperationId,
landTokenId: _landTokenId,
...
}
)

This increases readability for those unfamiliar with the contracts and reduces the chances of making a mistake with field ordering.

**Comment by programmablewealth** [comment]
implemented 👍
