### ISSUE TITLE
No need for == true

### ISSUE THREAD

**Issue by pakim249CAL** [programmablewealth/gotchiverse-crowdfarming-contracts#4]
https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/6487d7dca7cb93cd1448b315369956f2fff5203a/contracts/facets/CrowdFundingFacet.sol#L68

This is already a bool, so can be shortened to:

        require(s.farmingOperations[_operationId].landDeposited, "Land must be deposited for this farming operation");

**Comment by programmablewealth** [comment]
implemented 👍
