### ISSUE TITLE
Unnecesssary requires

### ISSUE THREAD

**Issue by pakim249CAL** [programmablewealth/gotchiverse-crowdfarming-contracts#5]
https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/6487d7dca7cb93cd1448b315369956f2fff5203a/contracts/facets/CrowdFundingFacet.sol#L37

https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/6487d7dca7cb93cd1448b315369956f2fff5203a/contracts/facets/CrowdFundingFacet.sol#L66

The transfer call will fail if the owner is not correct, so these checks are redundant. It's fine to keep them if it makes you feel more comfortable, but personally I think it's a wasted check.

**Comment by programmablewealth** [comment]
fixed 👍
