### ISSUE TITLE
Should be a view function

### ISSUE THREAD

**Issue by pakim249CAL** [programmablewealth/gotchiverse-crowdfarming-contracts#6]
https://github.com/programmablewealth/gotchiverse-crowdfarming-contracts/blob/6487d7dca7cb93cd1448b315369956f2fff5203a/contracts/facets/CrowdFundingFacet.sol#L75

It is important to label functions that do not modify state as view, as this helps ensure to contract readers that the function is safe from modifying any state.

**Comment by programmablewealth** [comment]
implemented 👍
